accounts/urls.py
from django.urls import path
from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

catalogue/urls.py
from django.urls import path
from . import views
from .views import PricesListCreateView, ShowListView

app_name = 'catalogue'

urlpatterns = [
    path('artist/', views.artist_index, name='artist-index'),  # route pour afficher tt les articles
    path('artist/<int:artist_id>/', views.artist_show, name='artist-show'),  # route pour afficher un seul artist
    path('artist/edit/<int:artist_id>/', views.artist.edit, name='artist-edit'),  # route pour editer un artist
    path('artist/create/', views.artist.create, name='artist-create'),  # route pour créer un artiste
    path('artist/delete/<int:artist_id>/', views.artist.delete, name='artist-delete'), # route pour supprimer un artiste
    path('api/prices/', PricesListCreateView.as_view(), name='price-list-create'),
    path('api/shows/', ShowListView.as_view(), name='show-list'),
    path('api/prices/<int:show_id>/', views.prices_by_show, name='prices-by-show'),
    # Route pour les tarifs par spectacle
]

reservations/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalogue/', include('catalogue.urls')),
    path(
        'admin/password_reset/',
        auth_views.PasswordResetView.as_view(
            extra_context={"site_header": admin.site.site_header}
        ),
        name="admin_password_reset",
    ),
    path(
        'admin/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            extra_context={"site_header": admin.site.site_header}
        ),
        name="password_reset_done",
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            extra_context={"site_header": admin.site.site_header}
        ),
        name="password_reset_confirm",
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            extra_context={"site_header": admin.site.site_header}
        ),
        name="password_reset_complete",
    ),
    path('admin/', admin.site.urls),
]

catalogue/models/artists.py
from django.db import models


class Artist(models.Model):
    firstname = models.CharField(max_length=60)
    lastname = models.CharField(max_length=60)

    def __str__(self):
        return self.firstname + " " + self.lastname

    class Meta:
        db_table = "artists"

catalogue/models/prices.py
from django.db import models

from catalogue.models.shows import Shows


class Prices(models.Model):
    type = models.CharField(max_length=30, null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    shows = models.ManyToManyField(Shows, related_name='shows')

    def __str__(self):
        return f"{self.type} - {self.price}"

catalogue/models/shows.py
from django.db import models


class Shows(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField()


    def __str__(self):
        return self.name

catalogue/models/user_meta.py
from django.contrib.auth.models import User
from django.db import models


class UserMeta(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    langue = models.CharField(max_length=2)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

    class Meta:
        db_table = "user_meta"

catalogue/forms/ArtistForm.py
from django import forms
from catalogue.models import Artist


class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ["firstname", "lastname",]

catalogue/views/artist.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from catalogue.forms.ArtistForm import ArtistForm
from catalogue.models import Artist
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.conf import settings


def group_required(*group_names):
    """
    Decorator that checks if the user is in the specified groups.
    """

    def in_groups(user):
        # Vérifie si l'utilisateur est authentifié
        if user.is_authenticated:
            # Vérifie si l'utilisateur appartient à l'un des groupes spécifiés
            if user.groups.filter(name__in=group_names).exists() or user.is_superuser:
                return True
        return False

    return user_passes_test(in_groups)


# Fonction pour afficher la liste de tous les artistes
def artist_index(request):
    artists = Artist.objects.all()  # récupere les artistes de la base de données
    return render(request, 'artist/index.html', context={'artists': artists})


# fonction pour afficher un artist
def artist_show(request, artist_id):
    try:
        artist = get_object_or_404(Artist, id=artist_id)  # récupere un seul artiste de la BDD
    except Artist.DoesNotExist:
        raise Http404('Artist inexistant')

    return render(request, 'artist/show.html', context={'artist': artist})


@login_required
@group_required('ADMIN')
def edit(request, artist_id):
    artist = get_object_or_404(Artist, id=artist_id)
    form = ArtistForm(request.POST or None, instance=artist)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Artiste modifié avec succès.")
            return redirect('catalogue:artist-show', artist_id=artist.id)
        else:
            messages.error(request, "Échec de la modification de l'artiste!")
    return render(request, 'artist/edit.html', {'form': form, 'artist': artist})


@login_required
@group_required('ADMIN')
def create(request):
    form = ArtistForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Nouvel artiste créé avec succès.")
            return redirect('catalogue:artist-index')

        else:
            messages.add_message(request, messages.ERROR, "Échec de l'ajout d'un nouvel artiste !")

    return render(request, 'artist/create.html', context={'form': form})


@login_required
@group_required('ADMIN')
@permission_required('catalog.can_delete', raise_exception=True)
def delete(request, artist_id):
    artist = get_object_or_404(Artist, id=artist_id)

    if request.method == "POST":
        artist.delete()
        messages.success(request, "Artiste supprimé avec succès.")

        return redirect('catalogue:artist-index')

    else:
        messages.error(request, "Échec de la suppression de l'artiste !")

    # Si la méthode n'est pas POST, rediriger vers la page de l'artiste
    return render(request, 'catalogue/artist/show.html', {
        'artist': artist,
    })

catalogue/views/pricesList.py
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from rest_framework.decorators import api_view

from rest_framework.response import Response
from catalogue.models import Prices, Shows
from catalogue.serializers import PricesSerializer, ShowSerializer

from rest_framework import generics
from catalogue.models import Prices
from catalogue.serializers import PricesSerializer
from catalogue.views import group_required


class ShowListView(generics.ListAPIView):
    queryset = Shows.objects.all()
    serializer_class = ShowSerializer


@method_decorator(group_required('Admin'), name='dispatch')
class PricesListCreateView(generics.ListCreateAPIView):
    queryset = Prices.objects.all()
    serializer_class = PricesSerializer


def prices_by_show(request, show_id):
    # Récupérer le spectacle correspondant à show_id
    show = get_object_or_404(Shows, id=show_id)

    # Récupérer les tarifs associés à ce spectacle
    prices = Prices.objects.filter(shows=show)

    # Renvoyer les informations au template
    return render(request, 'prices_by_show.html', {'show': show, 'prices': prices})

catalogue/templates/artist/create.html
{% extends 'layouts/base.html' %}

{% block title %}Ajouter un artiste{% endblock %}

{% block content %}
    <h2>Ajouter un artiste</h2>

    <form action="{% url 'catalogue:artist-create' %}" method="post">
        {% csrf_token %}

        {{ form }}
        <button>Ajouter</button>
        <a href="{% url 'catalogue:artist-index' %}">Annuler</a>
    </form>

    <nav><a href="{% url 'catalogue:artist-index' %}">Retour à l'index</a></nav>
{% endblock %}

catalogue/templates/artist/edit.html
{% extends 'layouts/base.html' %}

{% block title %}Modifier un artiste{% endblock %}

{% block content %}
    <h2>Modifier un artiste</h2>

    <form action="{% url 'catalogue:artist-edit' artist.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="_method" value="PUT">
        {{ form }}
        <button>Modifier</button>
        <a href="{% url 'catalogue:artist-show' artist.id %}">Annuler</a>
    </form>

    <nav><a href="{% url 'catalogue:artist-index' %}">Retour à l'index</a></nav>
{% endblock %}

catalogue/templates/artist/index.html
{% extends 'layouts/base.html' %}


{% block title %}Liste des artistes{% endblock %}


{% block content %}

    <h1>Liste des artistes</h1>

    <ul>
        <li><a href="{% url 'catalogue:artist-create' %}">Ajouter</a></li>
    </ul>

    <table>
        <thead>
            <tr>
                <th>Prénom</th>
                <th>Nom</th>
            </tr>
        </thead>
        <tbody>
        {% for artist in artists %}
            <tr>
                <td>{{ artist.firstname }}</td>
                <td><a href="{% url 'catalogue:artist-show' artist.id %}">{{ artist.lastname }}</a></td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="2">Aucun artiste trouvé dans la base de données.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

catalogue/templates/artist/show.html
{% extends 'layouts/base.html' %}


{% block title %}Fiche d'un artiste{% endblock %}


{% block content %}

    <h1>{{ artist.firstname }} {{ artist.lastname }}</h1>

    <div><a href="{% url 'catalogue:artist-edit' artist.id %}">Modifier</a></div>

    <form method="post" action="{% url 'catalogue:artist-delete' artist.id %}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet artiste ?')">
        {% csrf_token %}
        <input type="hidden" name="_method" value="DELETE">
        <button>Supprimer</button>
    </form>

    <nav><a href="{% url 'catalogue:artist-index' %}">Retour à la liste des artistes</a></nav>

{% endblock %}